package com.test.bean;
// Generated Oct 12, 2011 10:01:12 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Amphur generated by hbm2java
 */
@Entity
@Table(name = "AMPHUR")
public class Amphur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4900405049109623627L;
	private AmphurId id;
	private String amprDesc;
	private String amprCreatBy;
	private Date amprCreatDtm;
	private String amprMaintainBy;
	private Date amprMaintainDtm;

	public Amphur() {
	}

	public Amphur(AmphurId id) {
		this.id = id;
	}

	public Amphur(AmphurId id, String amprDesc, String amprCreatBy,
			Date amprCreatDtm, String amprMaintainBy, Date amprMaintainDtm) {
		this.id = id;
		this.amprDesc = amprDesc;
		this.amprCreatBy = amprCreatBy;
		this.amprCreatDtm = amprCreatDtm;
		this.amprMaintainBy = amprMaintainBy;
		this.amprMaintainDtm = amprMaintainDtm;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "amprPronProvnCd", column = @Column(name = "AMPR_PRON_PROVN_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "amprCd", column = @Column(name = "AMPR_CD", nullable = false, length = 3)),
			@AttributeOverride(name = "amprCtryCd", column = @Column(name = "AMPR_CTRY_CD", nullable = false, length = 2)) })
	public AmphurId getId() {
		return this.id;
	}

	public void setId(AmphurId id) {
		this.id = id;
	}

	@Column(name = "AMPR_DESC", length = 200)
	public String getAmprDesc() {
		return this.amprDesc;
	}

	public void setAmprDesc(String amprDesc) {
		this.amprDesc = amprDesc;
	}

	@Column(name = "AMPR_CREAT_BY", length = 30)
	public String getAmprCreatBy() {
		return this.amprCreatBy;
	}

	public void setAmprCreatBy(String amprCreatBy) {
		this.amprCreatBy = amprCreatBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AMPR_CREAT_DTM", length = 7)
	public Date getAmprCreatDtm() {
		return this.amprCreatDtm;
	}

	public void setAmprCreatDtm(Date amprCreatDtm) {
		this.amprCreatDtm = amprCreatDtm;
	}

	@Column(name = "AMPR_MAINTAIN_BY", length = 30)
	public String getAmprMaintainBy() {
		return this.amprMaintainBy;
	}

	public void setAmprMaintainBy(String amprMaintainBy) {
		this.amprMaintainBy = amprMaintainBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AMPR_MAINTAIN_DTM", length = 7)
	public Date getAmprMaintainDtm() {
		return this.amprMaintainDtm;
	}

	public void setAmprMaintainDtm(Date amprMaintainDtm) {
		this.amprMaintainDtm = amprMaintainDtm;
	}

}
