package com.test.bean;
// Generated Oct 12, 2011 10:01:12 AM by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AmphurId generated by hbm2java
 */
@Embeddable
public class AmphurId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1644618626659579935L;
	private String amprPronProvnCd;
     private String amprCd;
     private String amprCtryCd;

    public AmphurId() {
    }

    public AmphurId(String amprPronProvnCd, String amprCd, String amprCtryCd) {
       this.amprPronProvnCd = amprPronProvnCd;
       this.amprCd = amprCd;
       this.amprCtryCd = amprCtryCd;
    }
   

    @Column(name="AMPR_PRON_PROVN_CD", nullable=false, length=3)
    public String getAmprPronProvnCd() {
        return this.amprPronProvnCd;
    }
    
    public void setAmprPronProvnCd(String amprPronProvnCd) {
        this.amprPronProvnCd = amprPronProvnCd;
    }

    @Column(name="AMPR_CD", nullable=false, length=3)
    public String getAmprCd() {
        return this.amprCd;
    }
    
    public void setAmprCd(String amprCd) {
        this.amprCd = amprCd;
    }

    @Column(name="AMPR_CTRY_CD", nullable=false, length=2)
    public String getAmprCtryCd() {
        return this.amprCtryCd;
    }
    
    public void setAmprCtryCd(String amprCtryCd) {
        this.amprCtryCd = amprCtryCd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmphurId) ) return false;
		 AmphurId castOther = ( AmphurId ) other; 
         
		 return ( (this.getAmprPronProvnCd()==castOther.getAmprPronProvnCd()) || ( this.getAmprPronProvnCd()!=null && castOther.getAmprPronProvnCd()!=null && this.getAmprPronProvnCd().equals(castOther.getAmprPronProvnCd()) ) )
 && ( (this.getAmprCd()==castOther.getAmprCd()) || ( this.getAmprCd()!=null && castOther.getAmprCd()!=null && this.getAmprCd().equals(castOther.getAmprCd()) ) )
 && ( (this.getAmprCtryCd()==castOther.getAmprCtryCd()) || ( this.getAmprCtryCd()!=null && castOther.getAmprCtryCd()!=null && this.getAmprCtryCd().equals(castOther.getAmprCtryCd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAmprPronProvnCd() == null ? 0 : this.getAmprPronProvnCd().hashCode() );
         result = 37 * result + ( getAmprCd() == null ? 0 : this.getAmprCd().hashCode() );
         result = 37 * result + ( getAmprCtryCd() == null ? 0 : this.getAmprCtryCd().hashCode() );
         return result;
   }   


}


