package com.test.bean;

// Generated Oct 17, 2013 10:03:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BotBranchInstId generated by hbm2java
 */
@Entity
@Table(name = "BOT_BRANCH_INST_ID")
public class BotBranchInstId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long branchInstId;
	private BotPostalAddr botPostalAddrByFininstnidPstladrid;
	private BotPostalAddr botPostalAddrByBrnchidPstladrid;
	private String fininstnidBic;
	private String fininstnidClrsysmemidClrsysidCd;
	private String fininstnidClrsysmemidClrsysidPrtry;
	private String fininstnidClrsysmemidMmbid;
	private String fininstnidNm;
	private String fininstnidOthrId;
	private String fininstnidOthrSchmenmCd;
	private String fininstnidOthrSchmenmPrtry;
	private String fininstnidOthrIssr;
	private String brnchidId;
	private String brnchidNm;

	public BotBranchInstId() {
	}

	public BotBranchInstId(Long branchInstId) {
		this.branchInstId = branchInstId;
	}

	public BotBranchInstId(
			Long branchInstId,
			BotPostalAddr botPostalAddrByFininstnidPstladrid,
			BotPostalAddr botPostalAddrByBrnchidPstladrid,
			String fininstnidBic,
			String fininstnidClrsysmemidClrsysidCd,
			String fininstnidClrsysmemidClrsysidPrtry,
			String fininstnidClrsysmemidMmbid,
			String fininstnidNm,
			String fininstnidOthrId,
			String fininstnidOthrSchmenmCd,
			String fininstnidOthrSchmenmPrtry,
			String fininstnidOthrIssr,
			String brnchidId,
			String brnchidNm) {
		this.branchInstId = branchInstId;
		this.botPostalAddrByFininstnidPstladrid = botPostalAddrByFininstnidPstladrid;
		this.botPostalAddrByBrnchidPstladrid = botPostalAddrByBrnchidPstladrid;
		this.fininstnidBic = fininstnidBic;
		this.fininstnidClrsysmemidClrsysidCd = fininstnidClrsysmemidClrsysidCd;
		this.fininstnidClrsysmemidClrsysidPrtry = fininstnidClrsysmemidClrsysidPrtry;
		this.fininstnidClrsysmemidMmbid = fininstnidClrsysmemidMmbid;
		this.fininstnidNm = fininstnidNm;
		this.fininstnidOthrId = fininstnidOthrId;
		this.fininstnidOthrSchmenmCd = fininstnidOthrSchmenmCd;
		this.fininstnidOthrSchmenmPrtry = fininstnidOthrSchmenmPrtry;
		this.fininstnidOthrIssr = fininstnidOthrIssr;
		this.brnchidId = brnchidId;
		this.brnchidNm = brnchidNm;
	}

	@Id
	@Column(name = "BRANCH_INST_ID", unique = true, nullable = false, precision = 17, scale = 0)
	public Long getBranchInstId() {
		return this.branchInstId;
	}

	public void setBranchInstId(Long branchInstId) {
		this.branchInstId = branchInstId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FININSTNID_PSTLADRID")
	public BotPostalAddr getBotPostalAddrByFininstnidPstladrid() {
		return this.botPostalAddrByFininstnidPstladrid;
	}

	public void setBotPostalAddrByFininstnidPstladrid(
			BotPostalAddr botPostalAddrByFininstnidPstladrid) {
		this.botPostalAddrByFininstnidPstladrid = botPostalAddrByFininstnidPstladrid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRNCHID_PSTLADRID")
	public BotPostalAddr getBotPostalAddrByBrnchidPstladrid() {
		return this.botPostalAddrByBrnchidPstladrid;
	}

	public void setBotPostalAddrByBrnchidPstladrid(
			BotPostalAddr botPostalAddrByBrnchidPstladrid) {
		this.botPostalAddrByBrnchidPstladrid = botPostalAddrByBrnchidPstladrid;
	}

	@Column(name = "FININSTNID_BIC", length = 11)
	public String getFininstnidBic() {
		return this.fininstnidBic;
	}

	public void setFininstnidBic(String fininstnidBic) {
		this.fininstnidBic = fininstnidBic;
	}

	@Column(name = "FININSTNID_CLRSYSMEMID_CLRSYSID_CD", length = 5)
	public String getFininstnidClrsysmemidClrsysidCd() {
		return this.fininstnidClrsysmemidClrsysidCd;
	}

	public void setFininstnidClrsysmemidClrsysidCd(
			String fininstnidClrsysmemidClrsysidCd) {
		this.fininstnidClrsysmemidClrsysidCd = fininstnidClrsysmemidClrsysidCd;
	}

	@Column(name = "FININSTNID_CLRSYSMEMID_CLRSYSID_PRTRY", length = 35)
	public String getFininstnidClrsysmemidClrsysidPrtry() {
		return this.fininstnidClrsysmemidClrsysidPrtry;
	}

	public void setFininstnidClrsysmemidClrsysidPrtry(
			String fininstnidClrsysmemidClrsysidPrtry) {
		this.fininstnidClrsysmemidClrsysidPrtry = fininstnidClrsysmemidClrsysidPrtry;
	}

	@Column(name = "FININSTNID_CLRSYSMEMID_MMBID", length = 35)
	public String getFininstnidClrsysmemidMmbid() {
		return this.fininstnidClrsysmemidMmbid;
	}

	public void setFininstnidClrsysmemidMmbid(String fininstnidClrsysmemidMmbid) {
		this.fininstnidClrsysmemidMmbid = fininstnidClrsysmemidMmbid;
	}

	@Column(name = "FININSTNID_NM", length = 140)
	public String getFininstnidNm() {
		return this.fininstnidNm;
	}

	public void setFininstnidNm(String fininstnidNm) {
		this.fininstnidNm = fininstnidNm;
	}

	@Column(name = "FININSTNID_OTHR_ID", length = 35)
	public String getFininstnidOthrId() {
		return this.fininstnidOthrId;
	}

	public void setFininstnidOthrId(String fininstnidOthrId) {
		this.fininstnidOthrId = fininstnidOthrId;
	}

	@Column(name = "FININSTNID_OTHR_SCHMENM_CD", length = 5)
	public String getFininstnidOthrSchmenmCd() {
		return this.fininstnidOthrSchmenmCd;
	}

	public void setFininstnidOthrSchmenmCd(String fininstnidOthrSchmenmCd) {
		this.fininstnidOthrSchmenmCd = fininstnidOthrSchmenmCd;
	}

	@Column(name = "FININSTNID_OTHR_SCHMENM_PRTRY", length = 35)
	public String getFininstnidOthrSchmenmPrtry() {
		return this.fininstnidOthrSchmenmPrtry;
	}

	public void setFininstnidOthrSchmenmPrtry(String fininstnidOthrSchmenmPrtry) {
		this.fininstnidOthrSchmenmPrtry = fininstnidOthrSchmenmPrtry;
	}

	@Column(name = "FININSTNID_OTHR_ISSR", length = 35)
	public String getFininstnidOthrIssr() {
		return this.fininstnidOthrIssr;
	}

	public void setFininstnidOthrIssr(String fininstnidOthrIssr) {
		this.fininstnidOthrIssr = fininstnidOthrIssr;
	}

	@Column(name = "BRNCHID_ID", length = 35)
	public String getBrnchidId() {
		return this.brnchidId;
	}

	public void setBrnchidId(String brnchidId) {
		this.brnchidId = brnchidId;
	}

	@Column(name = "BRNCHID_NM", length = 140)
	public String getBrnchidNm() {
		return this.brnchidNm;
	}

	public void setBrnchidNm(String brnchidNm) {
		this.brnchidNm = brnchidNm;
	}

}
