package com.test.bean;

// Generated Oct 17, 2013 10:03:09 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BotGroupHeader generated by hbm2java
 */
@Entity
@Table(name = "BOT_GROUP_HEADER")
public class BotGroupHeader implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long groupHeaderId;
	private BotBranchInstId botBranchInstIdByFwdgagt;
	private BotPartyId botPartyId;
	private BotBranchInstId botBranchInstIdByCdtragt;
	private BotBranchInstId botBranchInstIdByDbtragt;
	private String msgid;
	private Date credttm;
	private String authorisation1choice1Cd;
	private String authorisation1choice1Prtry;
	private String authorisation1choice2Cd;
	private String authorisation1choice2Prtry;
	private Integer nboftxs;
	private BigDecimal ctrlsum;
	private String msgnmid;
	private String grpsts;
	private PaymentCollectionFees paymentCollectionFees;

	public BotGroupHeader() {
	}

	public BotGroupHeader(Long groupHeaderId, String msgid, Date credttm,
			Integer nboftxs) {
		this.groupHeaderId = groupHeaderId;
		this.msgid = msgid;
		this.credttm = credttm;
		this.nboftxs = nboftxs;
	}

	public BotGroupHeader(Long groupHeaderId,
			BotBranchInstId botBranchInstIdByFwdgagt, BotPartyId botPartyId,
			BotBranchInstId botBranchInstIdByCdtragt,
			BotBranchInstId botBranchInstIdByDbtragt, String msgid,
			Date credttm, String authorisation1choice1Cd,
			String authorisation1choice1Prtry, String authorisation1choice2Cd,
			String authorisation1choice2Prtry, Integer nboftxs, BigDecimal ctrlsum,
			String msgnmid, String grpsts,
			PaymentCollectionFees paymentCollectionFees) {
		this.groupHeaderId = groupHeaderId;
		this.botBranchInstIdByFwdgagt = botBranchInstIdByFwdgagt;
		this.botPartyId = botPartyId;
		this.botBranchInstIdByCdtragt = botBranchInstIdByCdtragt;
		this.botBranchInstIdByDbtragt = botBranchInstIdByDbtragt;
		this.msgid = msgid;
		this.credttm = credttm;
		this.authorisation1choice1Cd = authorisation1choice1Cd;
		this.authorisation1choice1Prtry = authorisation1choice1Prtry;
		this.authorisation1choice2Cd = authorisation1choice2Cd;
		this.authorisation1choice2Prtry = authorisation1choice2Prtry;
		this.nboftxs = nboftxs;
		this.ctrlsum = ctrlsum;
		this.msgnmid = msgnmid;
		this.grpsts = grpsts;
		this.paymentCollectionFees = paymentCollectionFees;
	}

	@Id
	@Column(name = "GROUP_HEADER_ID", unique = true, nullable = false, precision = 17, scale = 0)
	public Long getGroupHeaderId() {
		return this.groupHeaderId;
	}

	public void setGroupHeaderId(Long groupHeaderId) {
		this.groupHeaderId = groupHeaderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FWDGAGT")
	public BotBranchInstId getBotBranchInstIdByFwdgagt() {
		return this.botBranchInstIdByFwdgagt;
	}

	public void setBotBranchInstIdByFwdgagt(
			BotBranchInstId botBranchInstIdByFwdgagt) {
		this.botBranchInstIdByFwdgagt = botBranchInstIdByFwdgagt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INITGPTY")
	public BotPartyId getBotPartyId() {
		return this.botPartyId;
	}

	public void setBotPartyId(BotPartyId botPartyId) {
		this.botPartyId = botPartyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CDTRAGT")
	public BotBranchInstId getBotBranchInstIdByCdtragt() {
		return this.botBranchInstIdByCdtragt;
	}

	public void setBotBranchInstIdByCdtragt(
			BotBranchInstId botBranchInstIdByCdtragt) {
		this.botBranchInstIdByCdtragt = botBranchInstIdByCdtragt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DBTRAGT")
	public BotBranchInstId getBotBranchInstIdByDbtragt() {
		return this.botBranchInstIdByDbtragt;
	}

	public void setBotBranchInstIdByDbtragt(
			BotBranchInstId botBranchInstIdByDbtragt) {
		this.botBranchInstIdByDbtragt = botBranchInstIdByDbtragt;
	}

	@Column(name = "MSGID", nullable = false, length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREDTTM", nullable = false, length = 26)
	public Date getCredttm() {
		return this.credttm;
	}

	public void setCredttm(Date credttm) {
		this.credttm = credttm;
	}

	@Column(name = "AUTHORISATION1CHOICE_1_CD", length = 4)
	public String getAuthorisation1choice1Cd() {
		return this.authorisation1choice1Cd;
	}

	public void setAuthorisation1choice1Cd(String authorisation1choice1Cd) {
		this.authorisation1choice1Cd = authorisation1choice1Cd;
	}

	@Column(name = "AUTHORISATION1CHOICE_1_PRTRY", length = 128)
	public String getAuthorisation1choice1Prtry() {
		return this.authorisation1choice1Prtry;
	}

	public void setAuthorisation1choice1Prtry(String authorisation1choice1Prtry) {
		this.authorisation1choice1Prtry = authorisation1choice1Prtry;
	}

	@Column(name = "AUTHORISATION1CHOICE_2_CD", length = 4)
	public String getAuthorisation1choice2Cd() {
		return this.authorisation1choice2Cd;
	}

	public void setAuthorisation1choice2Cd(String authorisation1choice2Cd) {
		this.authorisation1choice2Cd = authorisation1choice2Cd;
	}

	@Column(name = "AUTHORISATION1CHOICE_2_PRTRY", length = 128)
	public String getAuthorisation1choice2Prtry() {
		return this.authorisation1choice2Prtry;
	}

	public void setAuthorisation1choice2Prtry(String authorisation1choice2Prtry) {
		this.authorisation1choice2Prtry = authorisation1choice2Prtry;
	}

	@Column(name = "NBOFTXS", nullable = false)
	public Integer getNboftxs() {
		return this.nboftxs;
	}

	public void setNboftxs(Integer nboftxs) {
		this.nboftxs = nboftxs;
	}

	@Column(name = "CTRLSUM", precision = 28, scale = 4)
	public BigDecimal getCtrlsum() {
		return this.ctrlsum;
	}

	public void setCtrlsum(BigDecimal ctrlsum) {
		this.ctrlsum = ctrlsum;
	}

	@Column(name = "MSGNMID", length = 35)
	public String getMsgnmid() {
		return this.msgnmid;
	}

	public void setMsgnmid(String msgnmid) {
		this.msgnmid = msgnmid;
	}

	@Column(name = "GRPSTS", length = 4)
	public String getGrpsts() {
		return this.grpsts;
	}

	public void setGrpsts(String grpsts) {
		this.grpsts = grpsts;
	}

	@OneToOne(fetch = FetchType.LAZY, optional=true, cascade = CascadeType.ALL)
	@JoinColumn(name="GROUP_HEADER_ID", referencedColumnName="GROUP_HEADER_ID")
	public PaymentCollectionFees getPaymentCollectionFees() {
		return this.paymentCollectionFees;
	}

	public void setPaymentCollectionFees(
			PaymentCollectionFees paymentCollectionFees) {
		this.paymentCollectionFees = paymentCollectionFees;
	}

}
