package com.test.bean;

// Generated Oct 17, 2013 10:03:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BotPostalAddr generated by hbm2java
 */
@Entity
@Table(name = "BOT_POSTAL_ADDR")
public class BotPostalAddr implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long postalAddrId;
	private String adrtp;
	private String dept;
	private String subdept;
	private String strtnm;
	private String bldgnb;
	private String pstcd;
	private String twnnm;
	private String ctrysubdvsn;
	private String ctry;
	private String adrline;

	public BotPostalAddr() {
	}

	public BotPostalAddr(Long postalAddrId) {
		this.postalAddrId = postalAddrId;
	}

	@Id
	@Column(name = "POSTAL_ADDR_ID", unique = true, nullable = false, precision = 17, scale = 0)
	public Long getPostalAddrId() {
		return this.postalAddrId;
	}

	public void setPostalAddrId(Long postalAddrId) {
		this.postalAddrId = postalAddrId;
	}

	@Column(name = "ADRTP", length = 4)
	public String getAdrtp() {
		return this.adrtp;
	}

	public void setAdrtp(String adrtp) {
		this.adrtp = adrtp;
	}

	@Column(name = "DEPT", length = 70)
	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	@Column(name = "SUBDEPT", length = 70)
	public String getSubdept() {
		return this.subdept;
	}

	public void setSubdept(String subdept) {
		this.subdept = subdept;
	}

	@Column(name = "STRTNM", length = 70)
	public String getStrtnm() {
		return this.strtnm;
	}

	public void setStrtnm(String strtnm) {
		this.strtnm = strtnm;
	}

	@Column(name = "BLDGNB", length = 16)
	public String getBldgnb() {
		return this.bldgnb;
	}

	public void setBldgnb(String bldgnb) {
		this.bldgnb = bldgnb;
	}

	@Column(name = "PSTCD", length = 16)
	public String getPstcd() {
		return this.pstcd;
	}

	public void setPstcd(String pstcd) {
		this.pstcd = pstcd;
	}

	@Column(name = "TWNNM", length = 35)
	public String getTwnnm() {
		return this.twnnm;
	}

	public void setTwnnm(String twnnm) {
		this.twnnm = twnnm;
	}

	@Column(name = "CTRYSUBDVSN", length = 35)
	public String getCtrysubdvsn() {
		return this.ctrysubdvsn;
	}

	public void setCtrysubdvsn(String ctrysubdvsn) {
		this.ctrysubdvsn = ctrysubdvsn;
	}

	@Column(name = "CTRY", length = 2)
	public String getCtry() {
		return this.ctry;
	}

	public void setCtry(String ctry) {
		this.ctry = ctry;
	}

	@Column(name = "ADRLINE", length = 70)
	public String getAdrline() {
		return this.adrline;
	}

	public void setAdrline(String adrline) {
		this.adrline = adrline;
	}

}
