package com.test.bean;

// Generated Oct 17, 2013 10:03:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BotPartyId generated by hbm2java
 */
@Entity
@Table(name = "BOT_PARTY_ID")
public class BotPartyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long partyId;
	private BotPostalAddr botPostalAddr;
	private String nm;
	private String idOrgidBicorbei;
	private Date idPrvtidDtandplcofbirthBirthdt;
	private String idPrvtidDtandplcofbirthPrvcofbirth;
	private String idPrvtidDtandplcofbirthCityofbirth;
	private String idPrvtidDtandplcofbirthCtryofbirth;
	private String ctryofres;
	private String ctctdtlsNmprfx;
	private String ctctdtlsNm;
	private String ctctdtlsPhnenb;
	private String ctctdtlsMobnb;
	private String ctctdtlsFaxnb;
	private String ctctdtlsEmailadr;
	private String ctctdtlsOthr;

	public BotPartyId() {
	}

	public BotPartyId(Long partyId) {
		this.partyId = partyId;
	}

	public BotPartyId(
			Long partyId,
			BotPostalAddr botPostalAddr,
			String nm,
			String idOrgidBicorbei,
			Date idPrvtidDtandplcofbirthBirthdt,
			String idPrvtidDtandplcofbirthPrvcofbirth,
			String idPrvtidDtandplcofbirthCityofbirth,
			String idPrvtidDtandplcofbirthCtryofbirth,
			String ctryofres,
			String ctctdtlsNmprfx,
			String ctctdtlsNm,
			String ctctdtlsPhnenb,
			String ctctdtlsMobnb,
			String ctctdtlsFaxnb,
			String ctctdtlsEmailadr,
			String ctctdtlsOthr) {
		this.partyId = partyId;
		this.botPostalAddr = botPostalAddr;
		this.nm = nm;
		this.idOrgidBicorbei = idOrgidBicorbei;
		this.idPrvtidDtandplcofbirthBirthdt = idPrvtidDtandplcofbirthBirthdt;
		this.idPrvtidDtandplcofbirthPrvcofbirth = idPrvtidDtandplcofbirthPrvcofbirth;
		this.idPrvtidDtandplcofbirthCityofbirth = idPrvtidDtandplcofbirthCityofbirth;
		this.idPrvtidDtandplcofbirthCtryofbirth = idPrvtidDtandplcofbirthCtryofbirth;
		this.ctryofres = ctryofres;
		this.ctctdtlsNmprfx = ctctdtlsNmprfx;
		this.ctctdtlsNm = ctctdtlsNm;
		this.ctctdtlsPhnenb = ctctdtlsPhnenb;
		this.ctctdtlsMobnb = ctctdtlsMobnb;
		this.ctctdtlsFaxnb = ctctdtlsFaxnb;
		this.ctctdtlsEmailadr = ctctdtlsEmailadr;
		this.ctctdtlsOthr = ctctdtlsOthr;
	}

	@Id
	@Column(name = "PARTY_ID", unique = true, nullable = false, precision = 17, scale = 0)
	public Long getPartyId() {
		return this.partyId;
	}

	public void setPartyId(Long partyId) {
		this.partyId = partyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PSTLADR")
	public BotPostalAddr getBotPostalAddr() {
		return this.botPostalAddr;
	}

	public void setBotPostalAddr(BotPostalAddr botPostalAddr) {
		this.botPostalAddr = botPostalAddr;
	}

	@Column(name = "NM", length = 140)
	public String getNm() {
		return this.nm;
	}

	public void setNm(String nm) {
		this.nm = nm;
	}

	@Column(name = "ID_ORGID_BICORBEI", length = 11)
	public String getIdOrgidBicorbei() {
		return this.idOrgidBicorbei;
	}

	public void setIdOrgidBicorbei(String idOrgidBicorbei) {
		this.idOrgidBicorbei = idOrgidBicorbei;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ID_PRVTID_DTANDPLCOFBIRTH_BIRTHDT", length = 26)
	public Date getIdPrvtidDtandplcofbirthBirthdt() {
		return this.idPrvtidDtandplcofbirthBirthdt;
	}

	public void setIdPrvtidDtandplcofbirthBirthdt(
			Date idPrvtidDtandplcofbirthBirthdt) {
		this.idPrvtidDtandplcofbirthBirthdt = idPrvtidDtandplcofbirthBirthdt;
	}

	@Column(name = "ID_PRVTID_DTANDPLCOFBIRTH_PRVCOFBIRTH", length = 35)
	public String getIdPrvtidDtandplcofbirthPrvcofbirth() {
		return this.idPrvtidDtandplcofbirthPrvcofbirth;
	}

	public void setIdPrvtidDtandplcofbirthPrvcofbirth(
			String idPrvtidDtandplcofbirthPrvcofbirth) {
		this.idPrvtidDtandplcofbirthPrvcofbirth = idPrvtidDtandplcofbirthPrvcofbirth;
	}

	@Column(name = "ID_PRVTID_DTANDPLCOFBIRTH_CITYOFBIRTH", length = 35)
	public String getIdPrvtidDtandplcofbirthCityofbirth() {
		return this.idPrvtidDtandplcofbirthCityofbirth;
	}

	public void setIdPrvtidDtandplcofbirthCityofbirth(
			String idPrvtidDtandplcofbirthCityofbirth) {
		this.idPrvtidDtandplcofbirthCityofbirth = idPrvtidDtandplcofbirthCityofbirth;
	}

	@Column(name = "ID_PRVTID_DTANDPLCOFBIRTH_CTRYOFBIRTH", length = 2)
	public String getIdPrvtidDtandplcofbirthCtryofbirth() {
		return this.idPrvtidDtandplcofbirthCtryofbirth;
	}

	public void setIdPrvtidDtandplcofbirthCtryofbirth(
			String idPrvtidDtandplcofbirthCtryofbirth) {
		this.idPrvtidDtandplcofbirthCtryofbirth = idPrvtidDtandplcofbirthCtryofbirth;
	}

	@Column(name = "CTRYOFRES", length = 2)
	public String getCtryofres() {
		return this.ctryofres;
	}

	public void setCtryofres(String ctryofres) {
		this.ctryofres = ctryofres;
	}

	@Column(name = "CTCTDTLS_NMPRFX", length = 4)
	public String getCtctdtlsNmprfx() {
		return this.ctctdtlsNmprfx;
	}

	public void setCtctdtlsNmprfx(String ctctdtlsNmprfx) {
		this.ctctdtlsNmprfx = ctctdtlsNmprfx;
	}

	@Column(name = "CTCTDTLS_NM", length = 140)
	public String getCtctdtlsNm() {
		return this.ctctdtlsNm;
	}

	public void setCtctdtlsNm(String ctctdtlsNm) {
		this.ctctdtlsNm = ctctdtlsNm;
	}

	@Column(name = "CTCTDTLS_PHNENB", length = 30)
	public String getCtctdtlsPhnenb() {
		return this.ctctdtlsPhnenb;
	}

	public void setCtctdtlsPhnenb(String ctctdtlsPhnenb) {
		this.ctctdtlsPhnenb = ctctdtlsPhnenb;
	}

	@Column(name = "CTCTDTLS_MOBNB", length = 30)
	public String getCtctdtlsMobnb() {
		return this.ctctdtlsMobnb;
	}

	public void setCtctdtlsMobnb(String ctctdtlsMobnb) {
		this.ctctdtlsMobnb = ctctdtlsMobnb;
	}

	@Column(name = "CTCTDTLS_FAXNB", length = 30)
	public String getCtctdtlsFaxnb() {
		return this.ctctdtlsFaxnb;
	}

	public void setCtctdtlsFaxnb(String ctctdtlsFaxnb) {
		this.ctctdtlsFaxnb = ctctdtlsFaxnb;
	}

	@Column(name = "CTCTDTLS_EMAILADR", length = 2048)
	public String getCtctdtlsEmailadr() {
		return this.ctctdtlsEmailadr;
	}

	public void setCtctdtlsEmailadr(String ctctdtlsEmailadr) {
		this.ctctdtlsEmailadr = ctctdtlsEmailadr;
	}

	@Column(name = "CTCTDTLS_OTHR", length = 35)
	public String getCtctdtlsOthr() {
		return this.ctctdtlsOthr;
	}

	public void setCtctdtlsOthr(String ctctdtlsOthr) {
		this.ctctdtlsOthr = ctctdtlsOthr;
	}

}
