package com.test.bean;

// Generated Oct 17, 2013 10:03:09 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentCollectionFees generated by hbm2java
 */
@Entity
@Table(name = "PAYMENT_COLLECTION_FEES")
public class PaymentCollectionFees implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long groupHeaderId;
	private BotGroupHeader botGroupHeader;
	private Date effDate;
	private String bankId;
	private String acctId;
	private BigDecimal amount;
	private String userref;
	private String status;

	public PaymentCollectionFees() {
	}

	public PaymentCollectionFees(BotGroupHeader botGroupHeader, Date effDate,
			String bankId, String acctId, BigDecimal amount) {
		this.botGroupHeader = botGroupHeader;
		this.effDate = effDate;
		this.bankId = bankId;
		this.acctId = acctId;
		this.amount = amount;
	}

	public PaymentCollectionFees(BotGroupHeader botGroupHeader, Date effDate,
			String bankId, String acctId, BigDecimal amount, String userref,
			String status) {
		this.botGroupHeader = botGroupHeader;
		this.effDate = effDate;
		this.bankId = bankId;
		this.acctId = acctId;
		this.amount = amount;
		this.userref = userref;
		this.status = status;
	}

	@Id
	@Column(name = "GROUP_HEADER_ID", unique = true, nullable = false, precision = 17, scale = 0)
	public Long getGroupHeaderId() {
		return this.groupHeaderId;
	}

	public void setGroupHeaderId(Long groupHeaderId) {
		this.groupHeaderId = groupHeaderId;
	}

	@OneToOne(optional=true, fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "paymentCollectionFees")
	@JoinColumn(name="GROUP_HEADER_ID", referencedColumnName="GROUP_HEADER_ID")
	public BotGroupHeader getBotGroupHeader() {
		return this.botGroupHeader;
	}

	public void setBotGroupHeader(BotGroupHeader botGroupHeader) {
		this.botGroupHeader = botGroupHeader;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFF_DATE", nullable = false, length = 26)
	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	@Column(name = "BANK_ID", nullable = false, length = 32)
	public String getBankId() {
		return this.bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	@Column(name = "ACCT_ID", nullable = false, length = 64)
	public String getAcctId() {
		return this.acctId;
	}

	public void setAcctId(String acctId) {
		this.acctId = acctId;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 18)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "USERREF", length = 125)
	public String getUserref() {
		return this.userref;
	}

	public void setUserref(String userref) {
		this.userref = userref;
	}

	@Column(name = "STATUS", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
