package com.test;
// Generated Jul 6, 2017 6:12:17 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.*;
import java.util.Date;

/**
 * WelfarePayeeComp generated by hbm2java
 */

/**
 * @author User
 *
 */
@Entity
@Table(name = "WELFARE_PAYEE_COMP", schema = "CORDBA")
public class WelfarePayeeComp implements java.io.Serializable {

	private long wpcSeqId;
	private String wpcWcComCode;
	private Long wpcCaufId;
	private long wpcCustCifKey;
	private String wpcPayeeAccNo;
	private String wpcWachAcc;
	private String wpcPayeeAccName;
	private String wpcStat;
	private String wpcCreateBy;
	private Date wpcCreateDtm;
	private String wpcMaintanBy;
	private Date wpcMaintainDtm;
	private Date wpcDocRefDate;
	private String wpcDocReqRef;
	private String wpcPayeeAccAlias;

	public WelfarePayeeComp() {
	}

	public WelfarePayeeComp(long wpcSeqId, String wpcWcComCode, long wpcCustCifKey) {
		this.wpcSeqId = wpcSeqId;
		this.wpcWcComCode = wpcWcComCode;
		this.wpcCustCifKey = wpcCustCifKey;
	}

	public WelfarePayeeComp(long wpcSeqId, String wpcWcComCode, Long wpcCaufId, long wpcCustCifKey,
                            String wpcPayeeAccNo, String wpcWachAcc, String wpcPayeeAccName, String wpcStat, String wpcCreateBy,
                            Date wpcCreateDtm, String wpcMaintanBy, Date wpcMaintainDtm, Date wpcDocRefDate, String wpcDocReqRef,
                            String wpcPayeeAccAlias) {
		this.wpcSeqId = wpcSeqId;
		this.wpcWcComCode = wpcWcComCode;
		this.wpcCaufId = wpcCaufId;
		this.wpcCustCifKey = wpcCustCifKey;
		this.wpcPayeeAccNo = wpcPayeeAccNo;
		this.wpcWachAcc = wpcWachAcc;
		this.wpcPayeeAccName = wpcPayeeAccName;
		this.wpcStat = wpcStat;
		this.wpcCreateBy = wpcCreateBy;
		this.wpcCreateDtm = wpcCreateDtm;
		this.wpcMaintanBy = wpcMaintanBy;
		this.wpcMaintainDtm = wpcMaintainDtm;
		this.wpcDocRefDate = wpcDocRefDate;
		this.wpcDocReqRef = wpcDocReqRef;
		this.wpcPayeeAccAlias = wpcPayeeAccAlias;
	}

	@Id

	@Column(name = "WPC_SEQ_ID", unique = true, nullable = false, precision = 17, scale = 0)
	public long getWpcSeqId() {
		return this.wpcSeqId;
	}

	public void setWpcSeqId(long wpcSeqId) {
		this.wpcSeqId = wpcSeqId;
	}

	@Column(name = "WPC_WC_COM_CODE", nullable = false, length = 50)
	public String getWpcWcComCode() {
		return this.wpcWcComCode;
	}

	public void setWpcWcComCode(String wpcWcComCode) {
		this.wpcWcComCode = wpcWcComCode;
	}

	@Column(name = "WPC_CAUF_ID", precision = 17, scale = 0)
	public Long getWpcCaufId() {
		return this.wpcCaufId;
	}

	public void setWpcCaufId(Long wpcCaufId) {
		this.wpcCaufId = wpcCaufId;
	}

	@Column(name = "WPC_CUST_CIF_KEY", nullable = false, precision = 12, scale = 0)
	public long getWpcCustCifKey() {
		return this.wpcCustCifKey;
	}

	public void setWpcCustCifKey(long wpcCustCifKey) {
		this.wpcCustCifKey = wpcCustCifKey;
	}

	@Column(name = "WPC_PAYEE_ACC_NO", length = 20)
	public String getWpcPayeeAccNo() {
		return this.wpcPayeeAccNo;
	}

	public void setWpcPayeeAccNo(String wpcPayeeAccNo) {
		this.wpcPayeeAccNo = wpcPayeeAccNo;
	}

	@Column(name = "WPC_WACH_ACC", length = 20)
	public String getWpcWachAcc() {
		return this.wpcWachAcc;
	}

	public void setWpcWachAcc(String wpcWachAcc) {
		this.wpcWachAcc = wpcWachAcc;
	}

	@Column(name = "WPC_PAYEE_ACC_NAME", length = 160)
	public String getWpcPayeeAccName() {
		return this.wpcPayeeAccName;
	}

	public void setWpcPayeeAccName(String wpcPayeeAccName) {
		this.wpcPayeeAccName = wpcPayeeAccName;
	}

	@Column(name = "WPC_STAT", length = 5)
	public String getWpcStat() {
		return this.wpcStat;
	}

	public void setWpcStat(String wpcStat) {
		this.wpcStat = wpcStat;
	}

	@Column(name = "WPC_CREATE_BY", length = 30)
	public String getWpcCreateBy() {
		return this.wpcCreateBy;
	}

	public void setWpcCreateBy(String wpcCreateBy) {
		this.wpcCreateBy = wpcCreateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WPC_CREATE_DTM", length = 26)
	public Date getWpcCreateDtm() {
		return this.wpcCreateDtm;
	}

	public void setWpcCreateDtm(Date wpcCreateDtm) {
		this.wpcCreateDtm = wpcCreateDtm;
	}

	@Column(name = "WPC_MAINTAN_BY", length = 30)
	public String getWpcMaintanBy() {
		return this.wpcMaintanBy;
	}

	public void setWpcMaintanBy(String wpcMaintanBy) {
		this.wpcMaintanBy = wpcMaintanBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WPC_MAINTAIN_DTM", length = 26)
	public Date getWpcMaintainDtm() {
		return this.wpcMaintainDtm;
	}

	public void setWpcMaintainDtm(Date wpcMaintainDtm) {
		this.wpcMaintainDtm = wpcMaintainDtm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WPC_DOC_REF_DATE", length = 26)
	public Date getWpcDocRefDate() {
		return this.wpcDocRefDate;
	}

	public void setWpcDocRefDate(Date wpcDocRefDate) {
		this.wpcDocRefDate = wpcDocRefDate;
	}

	@Column(name = "WPC_DOC_REQ_REF", length = 40)
	public String getWpcDocReqRef() {
		return this.wpcDocReqRef;
	}

	public void setWpcDocReqRef(String wpcDocReqRef) {
		this.wpcDocReqRef = wpcDocReqRef;
	}

	@Column(name = "WPC_PAYEE_ACC_ALIAS", length = 200)
	public String getWpcPayeeAccAlias() {
		return this.wpcPayeeAccAlias;
	}

	public void setWpcPayeeAccAlias(String wpcPayeeAccAlias) {
		this.wpcPayeeAccAlias = wpcPayeeAccAlias;
	}

	@Override
	public String toString() {
		return "WelfarePayeeComp [wpcSeqId=" + wpcSeqId + ", wpcWcComCode=" + wpcWcComCode + ", wpcCaufId=" + wpcCaufId
				+ ", wpcCustCifKey=" + wpcCustCifKey + ", wpcPayeeAccNo=" + wpcPayeeAccNo + ", wpcWachAcc=" + wpcWachAcc
				+ ", wpcPayeeAccName=" + wpcPayeeAccName + ", wpcStat=" + wpcStat + ", wpcCreateBy=" + wpcCreateBy
				+ ", wpcCreateDtm=" + wpcCreateDtm + ", wpcMaintanBy=" + wpcMaintanBy + ", wpcMaintainDtm="
				+ wpcMaintainDtm + ", wpcDocRefDate=" + wpcDocRefDate + ", wpcDocReqRef=" + wpcDocReqRef
				+ ", wpcPayeeAccAlias=" + wpcPayeeAccAlias + "]";
	}

}
